development:
  adapter: postgresql
  encoding: unicode
  database: t_emails
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: t_emails_test
  pool: 5
  username: gschool
  password:
